diary 'sourcedata/eeg/sub-s01.log';
%% CHECK FOR OUTPUT PATH AND CRETAE IF NECESSARY
system('mkdir -p sub-s01/eeg');
eeg_init({'sourcedata/eeg/IC_trn_P01_O_1.bdf', ...
          'sourcedata/eeg/IC_trn_P01_O_2.bdf', ...
          'sourcedata/eeg/IC_trn_P01_O_3.bdf', ...
          'sourcedata/eeg/IC_trn_P01_O_4.bdf'}, ...
          'sub-s01/eeg/sub-s01_task-faceO_eeg.set');
         
diary 'sourcedata/eeg/sub-s02.log';
%% CHECK FOR OUTPUT PATH AND CRETAE IF NECESSARY
system('mkdir -p sub-s02/eeg');
eeg_init({'sourcedata/eeg/IC_trn_P02_O_1.bdf', ...
          'sourcedata/eeg/IC_trn_P02_O_2.bdf', ...
          'sourcedata/eeg/IC_trn_P02_O_3.bdf', ...
          'sourcedata/eeg/IC_trn_P02_O_4.bdf'}, ...
          'sub-s02/eeg/sub-s02_task-faceO_eeg.set');

diary 'sourcedata/eeg/sub-s03.log';
%% CHECK FOR OUTPUT PATH AND CRETAE IF NECESSARY
system('mkdir -p sub-s03/eeg');
eeg_init({'sourcedata/eeg/IC_trn_P03_O_1.bdf', ...
          'sourcedata/eeg/IC_trn_P03_O_2.bdf', ...
          'sourcedata/eeg/IC_trn_P03_O_3.bdf', ...
          'sourcedata/eeg/IC_trn_P03_O_4.bdf'}, ...
          'sub-s03/eeg/sub-s03_task-faceO_eeg.set');

diary 'sourcedata/eeg/sub-s04.log';
%% CHECK FOR OUTPUT PATH AND CRETAE IF NECESSARY
system('mkdir -p sub-s04/eeg');
eeg_init({'sourcedata/eeg/IC_trn_P04_O_1.bdf', ...
          'sourcedata/eeg/IC_trn_P04_O_2.bdf', ...
          'sourcedata/eeg/IC_trn_P04_O_3.bdf', ...
          'sourcedata/eeg/IC_trn_P04_O_4.bdf'}, ...
          'sub-s04/eeg/sub-s04_task-faceO_eeg.set');

diary 'sourcedata/eeg/sub-s05.log';
%% CHECK FOR OUTPUT PATH AND CRETAE IF NECESSARY
system('mkdir -p sub-s05/eeg');
eeg_init({'sourcedata/eeg/IC_trn_P05_O_1.bdf', ...
          'sourcedata/eeg/IC_trn_P05_O_2.bdf', ...
          'sourcedata/eeg/IC_trn_P05_O_3.bdf', ...
          'sourcedata/eeg/IC_trn_P05_O_4.bdf'}, ...
          'sub-s05/eeg/sub-s05_task-faceO_eeg.set');
      
diary 'sourcedata/eeg/sub-s06.log';
%% CHECK FOR OUTPUT PATH AND CRETAE IF NECESSARY
system('mkdir -p sub-s06/eeg');
eeg_init({'sourcedata/eeg/IC_trn_P06_O_1.bdf', ...
          'sourcedata/eeg/IC_trn_P06_O_2.bdf', ...
          'sourcedata/eeg/IC_trn_P06_O_3.bdf', ...
          'sourcedata/eeg/IC_trn_P06_O_4.bdf'}, ...
          'sub-s06/eeg/sub-s06_task-faceO_eeg.set');

diary 'sourcedata/eeg/sub-s07.log';
%% CHECK FOR OUTPUT PATH AND CRETAE IF NECESSARY
system('mkdir -p sub-s07/eeg');
eeg_init({'sourcedata/eeg/IC_trn_P07_O_1.bdf', ...
          'sourcedata/eeg/IC_trn_P07_O_2.bdf', ...
          'sourcedata/eeg/IC_trn_P07_O_3.bdf', ...
          'sourcedata/eeg/IC_trn_P07_O_4.bdf'}, ...
          'sub-s07/eeg/sub-s07_task-faceO_eeg.set');

diary 'sourcedata/eeg/sub-s08.log';
%% CHECK FOR OUTPUT PATH AND CRETAE IF NECESSARY
system('mkdir -p sub-s08/eeg');
eeg_init({'sourcedata/eeg/IC_trn_P08_O_1.bdf', ...
          'sourcedata/eeg/IC_trn_P08_O_2.bdf', ...
          'sourcedata/eeg/IC_trn_P08_O_3.bdf', ...
          'sourcedata/eeg/IC_trn_P08_O_4.bdf'}, ...
          'sub-s08/eeg/sub-s08_task-faceO_eeg.set');

diary 'sourcedata/eeg/sub-s09.log';
%% CHECK FOR OUTPUT PATH AND CRETAE IF NECESSARY
system('mkdir -p sub-s09/eeg');
eeg_init({'sourcedata/eeg/IC_trn_P09_O_1.bdf', ...
          'sourcedata/eeg/IC_trn_P09_O_2.bdf', ...
          'sourcedata/eeg/IC_trn_P09_O_3.bdf', ...
          'sourcedata/eeg/IC_trn_P09_O_4.bdf'}, ...
          'sub-s09/eeg/sub-s09_task-faceO_eeg.set');

diary 'sourcedata/eeg/sub-s10.log';
%% CHECK FOR OUTPUT PATH AND CRETAE IF NECESSARY
system('mkdir -p sub-s10/eeg');
eeg_init({'sourcedata/eeg/IC_trn_P10_O_1.bdf', ...
          'sourcedata/eeg/IC_trn_P10_O_2.bdf', ...
          'sourcedata/eeg/IC_trn_P10_O_3.bdf', ...
          'sourcedata/eeg/IC_trn_P10_O_4.bdf'}, ...
          'sub-s10/eeg/sub-s10_task-faceO_eeg.set');