%FHBC_fade
EEG = pop_marks_event_gap(EEG,{'-f'},3000,'in_task_fhbc_fade',[.7 .7 1], ...
				'interval','off', ...
				'critdir','max', ...
				'exact','off', ...
				'offsets',[3000 -3000], ...
				'ref_point','both', ...
				'invert_flags','on');
EEG = pop_marks_event_gap(EEG,{'-f'},3000,'in_leadup_fhbc_fade',[.4 .4 1], ...
				'interval','off', ...
				'critdir','max', ...
				'exact','off', ...
				'offsets',[-4000 4000], ...
				'ref_point','second', ...
				'invert_flags','off');

%FHBC_onset
EEG = pop_marks_event_gap(EEG,{'face-upright', ...
                               'face-inverted', ...
                               'house-upright', ...
                               'house-inverted', ...
                               'checker-left', ...
                               'checker-right'}, ...
                3000,'in_task_fhbc_onset',[.7 1 .7], ...
				'interval','off', ...
				'critdir','max', ...
				'exact','on', ...
				'offsets',[3000 -3000], ...
				'ref_point','both', ...
				'invert_flags','on');
EEG = pop_marks_event_gap(EEG,{'face-upright', ...
                               'face-inverted', ...
                               'house-upright', ...
                               'house-inverted', ...
                               'checker-left', ...
                               'checker-right'}, ...
                3000,'in_leadup_fhbc_onset',[.4 1 .4], ...
				'interval','off', ...
				'critdir','max', ...
				'exact','on', ...
				'offsets',[-4000 4000], ...
				'ref_point','second', ...
				'invert_flags','off');

%mark out_task
gapflags=marks_label2index(EEG.marks.time_info,{'in_task'},'flags','exact','off');
EEG.marks=marks_add_label(EEG.marks,'time_info',{'out_task',[0 0 0],~gapflags});

%MARK FLAG GAPS THAT ARE < 2 SECONDS...
EEG=pop_marks_flag_gap(EEG,{'manual','out_task'},2000,'mark_gap',[.2,.2,.2],'offsets',[0 0],'ref_point','both');

%COMBINE MARKS STRUCTURE INTO MANUAL FLAGS....
EEG=pop_marks_merge_labels(EEG,'time_info',{'manual', ...
                                            'out_task', ...
                                            'mark_gap', ...
                                            'in_leadup_fhbc_fade', ...
                                            'in_leadup_fhbc_onset'}, ...
                                            'target_label','manual');


