init_bids_all('bids/derivatives/lossless/','_ll', ...
        'TaskName','FaceFO', ...
        'TaskDescription','Visual presentation of oval cropped face and house images both upright and inverted. rare left and right half oval checkerboards were presetned as targets.', ...
        'Instrctions','Fixate on the "+" in the middle of the monitor, when ther is a half oval checkerboard to the left or right of the fication respond with your respectiveindex finger button press',...
        'InstitutionName','Brock University',...
        'InstitutionAddress','500 Glenrifge Ave, St.Catharines, Ontario', ...
        'PowerLineFrequency','60', ...
        'EEGPlacementScheme','Custom equidistant developped with McMaster University',...
        'Manufacturer','BioSemi',...
        'ManufacturerModelName','ActiveTwo',...
        'HardwareFilters','DC to Nyquist 512Hz',...
        'SoftwareFilters','1Hz to 30Hz, highpass and lowpass residuals save to *_hpd.mat and *_lpd.mat for full spectrum recovery.',...
        'DeviceSoftwareVersion','ActiView LabView',...
        'SubjectArtifactDescription','Movement artifacts as well as biological artifacts (e.g. blinks and eye movements) were mostly isolated to periods flagged in the EEG.marks.time_info annotation labeled "out_task". The lossless pipeline identified artifactual channels, components and time points and flagged them in the "manual" marks EEG.marks.chan_info(1).flags, EEG.marks.comp_info(1).flags and EEG.marks.time_info(1).flags respectively. Other Marks labels in the EEG.marks structure identify specific reasons for rejection.');