init_bids_all('bids/derivatives/lossless/derivatives/segmentation','_housi', ...
        'TaskName','FaceFO', ...
        'TaskDescription','Visual presentation of oval cropped face and house images both upright and inverted. rare left and right half oval checkerboards were presetned as targets.', ...
        'Instrctions','Fixate on the "+" in the middle of the monitor, when ther is a half oval checkerboard to the left or right of the fication respond with your respectiveindex finger button press',...
        'InstitutionName','Brock University',...
        'InstitutionAddress','500 Glenrifge Ave, St.Catharines, Ontario', ...
        'PowerLineFrequency','60', ...
        'EEGPlacementScheme','Custom equidistant developped with McMaster University',...
        'Manufacturer','BioSemi',...
        'ManufacturerModelName','ActiveTwo',...
        'HardwareFilters','DC to Nyquist 512Hz',...
        'SoftwareFilters','1Hz to 30Hz, highpass and lowpass residuals save to *_hpd.mat and *_lpd.mat for full spectrum recovery.',...
        'DeviceSoftwareVersion','ActiView LabView',...
        'SubjectArtifactDescription','Artifacts were removed in the continuous data prior to segmentation based on "manual" labeled marks initially classified by the lossless pipeline then visually inspected and modified where necessary.', ...
        'Category','House-Inverted');