diary 'bids/source/eeg/sub-s01.log';
eeg_init({'bids/source/eeg/IC_trn_P01_F_1.bdf', ...
          'bids/source/eeg/IC_trn_P01_F_2.bdf', ...
          'bids/source/eeg/IC_trn_P01_f_3.bdf', ...
          'bids/source/eeg/IC_trn_P01_f_4.bdf', ...
          'bids/source/eeg/IC_trn_P01_O_1.bdf', ...
          'bids/source/eeg/IC_trn_P01_O_2.bdf', ...
          'bids/source/eeg/IC_trn_P01_O_3.bdf', ...
          'bids/source/eeg/IC_trn_P01_O_4.bdf'}, ...
          'bids/sub-s01/eeg/sub-s01_task-faceFO_eeg.set');
         
diary 'bids/source/eeg/sub-s02.log';
eeg_init({'bids/source/eeg/IC_trn_P02_F_1.bdf', ...
          'bids/source/eeg/IC_trn_P02_F_2.bdf', ...
          'bids/source/eeg/IC_trn_P02_F_3.bdf', ...
          'bids/source/eeg/IC_trn_P02_F_4.bdf', ...
          'bids/source/eeg/IC_trn_P02_O_1.bdf', ...
          'bids/source/eeg/IC_trn_P02_O_2.bdf', ...
          'bids/source/eeg/IC_trn_P02_O_3.bdf', ...
          'bids/source/eeg/IC_trn_P02_O_4.bdf'}, ...
          'bids/sub-s02/eeg/sub-s02_task-faceFO_eeg.set');

diary 'bids/source/eeg/sub-s03.log';
eeg_init({'bids/source/eeg/IC_trn_P03_F_1.bdf', ...
          'bids/source/eeg/IC_trn_P03_F_2.bdf', ...
          'bids/source/eeg/IC_trn_P03_F_3.bdf', ...
          'bids/source/eeg/IC_trn_P03_F_4.bdf', ...
          'bids/source/eeg/IC_trn_P03_O_1.bdf', ...
          'bids/source/eeg/IC_trn_P03_O_2.bdf', ...
          'bids/source/eeg/IC_trn_P03_O_3.bdf', ...
          'bids/source/eeg/IC_trn_P03_O_4.bdf'}, ...
          'bids/sub-s03/eeg/sub-s03_task-faceFO_eeg.set');

diary 'bids/source/eeg/sub-s04.log';
eeg_init({'bids/source/eeg/IC_trn_P04_F_1.bdf', ...
          'bids/source/eeg/IC_trn_P04_F_2.bdf', ...
          'bids/source/eeg/IC_trn_P04_F_3.bdf', ...
          'bids/source/eeg/IC_trn_P04_F_4.bdf', ...
          'bids/source/eeg/IC_trn_P04_O_1.bdf', ...
          'bids/source/eeg/IC_trn_P04_O_2.bdf', ...
          'bids/source/eeg/IC_trn_P04_O_3.bdf', ...
          'bids/source/eeg/IC_trn_P04_O_4.bdf'}, ...
          'bids/sub-s04/eeg/sub-s04_task-faceFO_eeg.set');

diary 'bids/source/eeg/sub-s05.log';
eeg_init({'bids/source/eeg/IC_trn_P05_F_1.bdf', ...
          'bids/source/eeg/IC_trn_P05_F_2.bdf', ...
          'bids/source/eeg/IC_trn_P05_F_3.bdf', ...
          'bids/source/eeg/IC_trn_P05_F_4.bdf', ...
          'bids/source/eeg/IC_trn_P05_O_1.bdf', ...
          'bids/source/eeg/IC_trn_P05_O_2.bdf', ...
          'bids/source/eeg/IC_trn_P05_O_3.bdf', ...
          'bids/source/eeg/IC_trn_P05_O_4.bdf'}, ...
          'bids/sub-s05/eeg/sub-s05_task-faceFO_eeg.set');

diary 'bids/source/eeg/sub-s06.log';
eeg_init({'bids/source/eeg/IC_trn_P06_F_1.bdf', ...
          'bids/source/eeg/IC_trn_P06_F_2.bdf', ...
          'bids/source/eeg/IC_trn_P06_F_3.bdf', ...
          'bids/source/eeg/IC_trn_P06_F_4.bdf', ...
          'bids/source/eeg/IC_trn_P06_O_1.bdf', ...
          'bids/source/eeg/IC_trn_P06_O_2.bdf', ...
          'bids/source/eeg/IC_trn_P06_O_3.bdf', ...
          'bids/source/eeg/IC_trn_P06_O_4.bdf'}, ...
          'bids/sub-s06/eeg/sub-s06_task-faceFO_eeg.set');

diary 'bids/source/eeg/sub-s07.log';
eeg_init({'bids/source/eeg/IC_trn_P07_F_1.bdf', ...
          'bids/source/eeg/IC_trn_P07_F_2.bdf', ...
          'bids/source/eeg/IC_trn_P07_F_3.bdf', ...
          'bids/source/eeg/IC_trn_P07_F_4.bdf', ...
          'bids/source/eeg/IC_trn_P07_O_1.bdf', ...
          'bids/source/eeg/IC_trn_P07_O_2.bdf', ...
          'bids/source/eeg/IC_trn_P07_O_3.bdf', ...
          'bids/source/eeg/IC_trn_P07_O_4.bdf'}, ...
          'bids/sub-s07/eeg/sub-s07_task-faceFO_eeg.set');

diary 'bids/source/eeg/sub-s08.log';
eeg_init({'bids/source/eeg/IC_trn_P08_F_1.bdf', ...
          'bids/source/eeg/IC_trn_P08_F_2.bdf', ...
          'bids/source/eeg/IC_trn_P08_F_3.bdf', ...
          'bids/source/eeg/IC_trn_P08_F_4.bdf', ...
          'bids/source/eeg/IC_trn_P08_O_1.bdf', ...
          'bids/source/eeg/IC_trn_P08_O_2.bdf', ...
          'bids/source/eeg/IC_trn_P08_O_3.bdf', ...
          'bids/source/eeg/IC_trn_P08_O_4.bdf'}, ...
          'bids/sub-s08/eeg/sub-s08_task-faceFO_eeg.set');

diary 'bids/source/eeg/sub-s09.log';
eeg_init({'bids/source/eeg/IC_trn_P09_F_1.bdf', ...
          'bids/source/eeg/IC_trn_P09_F_2.bdf', ...
          'bids/source/eeg/IC_trn_P09_F_3.bdf', ...
          'bids/source/eeg/IC_trn_P09_F_4.bdf', ...
          'bids/source/eeg/IC_trn_P09_O_1.bdf', ...
          'bids/source/eeg/IC_trn_P09_O_2.bdf', ...
          'bids/source/eeg/IC_trn_P09_O_3.bdf', ...
          'bids/source/eeg/IC_trn_P09_O_4.bdf'}, ...
          'bids/sub-s09/eeg/sub-s09_task-faceFO_eeg.set');

diary 'bids/source/eeg/sub-s10.log';
eeg_init({'bids/source/eeg/IC_trn_P10_F_1.bdf', ...
          'bids/source/eeg/IC_trn_P10_F_2.bdf', ...
          'bids/source/eeg/IC_trn_P10_F_3.bdf', ...
          'bids/source/eeg/IC_trn_P10_F_4.bdf', ...
          'bids/source/eeg/IC_trn_P10_O_1.bdf', ...
          'bids/source/eeg/IC_trn_P10_O_2.bdf', ...
          'bids/source/eeg/IC_trn_P10_O_3.bdf', ...
          'bids/source/eeg/IC_trn_P10_O_4.bdf'}, ...
          'bids/sub-s10/eeg/sub-s10_task-faceFO_eeg.set');
